#!/bin/bash
ID=$1
KRN=$(find -wholename "./scores/*/krn/${ID}.krn")
LMXE=$(find -wholename "./scores/*/lmxe/${ID}.lmxe")
IMG=$(find -wholename "./scores/*/crop_resized/${ID}.png")
echo $IMG
imcat $IMG
echo ""
# echo $KRN
# cat $KRN
echo $LMXE
cat $LMXE
