from pathlib import Path
import shutil
from itertools import groupby

import xml
import xml.etree.ElementTree as ET

import music21
from difflib import SequenceMatcher


def strip_invisible_elements(tree:ET.ElementTree, remove_position_modifications=False) -> ET.ElementTree:
  """
  remove all <El print-object="no"/>
  using etree
  """
  root = tree.getroot()

  for measure in reversed(root.findall('.//measure')):
    for el in reversed(measure.findall('.//note[@print-object="no"]')):
      measure.remove(el)
  
    if remove_position_modifications:
      for el in reversed(measure.findall('.//backup')):
        measure.remove(el)
      for el in reversed(measure.findall('.//forward')):
        measure.remove(el)

  return ET.ElementTree(root)

"""
Most of the Diagnose functions are generated by Claude Sonnet 4
"""
class DiagnoseFunctions:
  pass


def remove_consecutive_items(seq):
  return [key for key, _ in groupby(seq)]



def is_chord(element):
  """Check if element is a chord"""
  return isinstance(element, music21.chord.Chord)


def compare_note_sequences(file1, file2, tolerance=0.01):
  """Direct comparison of note sequences without MIDI conversion"""
  try:
    score1 = music21.converter.parse(file1)
  except:
    parser = music21.musicxml.xmlToM21.MusicXMLImporter()
    score1 = parser.scoreFromFile(file1)
  
  try:
    score2 = music21.converter.parse(file2)
  except:
    parser = music21.musicxml.xmlToM21.MusicXMLImporter()
    score2 = parser.scoreFromFile(file2)

  def extract_note_data(score):
    """Extract normalized note data from score"""
    notes_data = []
    
    for element in score.flatten().notesAndRests:
      if isinstance(element, music21.note.Note):
        notes_data.append({
          'type': 'note',
          'pitch': element.pitch.midi,
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
      elif isinstance(element, music21.chord.Chord):
        notes_data.append({
          'type': 'chord',
          'pitches': tuple(sorted(p.midi for p in element.pitches)),
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
      elif isinstance(element, music21.note.Rest):
        notes_data.append({
          'type': 'rest',
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
    
    return notes_data
  
  notes1 = extract_note_data(score1)
  notes2 = extract_note_data(score2)
  
  if len(notes1) != len(notes2):
    return False, f"Note count differs: {len(notes1)} vs {len(notes2)}"
  
  # Compare note by note with tolerance for floating point
  for i, (n1, n2) in enumerate(zip(notes1, notes2)):
    if n1['type'] != n2['type']:
      return False, f"Note {i}: type differs {n1['type']} vs {n2['type']}"
    
    if abs(n1['offset'] - n2['offset']) > tolerance:
      return False, f"Note {i}: offset differs {n1['offset']} vs {n2['offset']}"
    
    if abs(n1['duration'] - n2['duration']) > tolerance:
      return False, f"Note {i}: duration differs {n1['duration']} vs {n2['duration']}"
    
    if n1['type'] == 'note' and n1['pitch'] != n2['pitch']:
      return False, f"Note {i}: pitch differs {n1['pitch']} vs {n2['pitch']}"
    
    if n1['type'] == 'chord' and n1['pitches'] != n2['pitches']:
      return False, f"Chord {i}: pitches differ {n1['pitches']} vs {n2['pitches']}"
  
  return True, "Files are identical"


class NoteComparisonFunctions:
  pass


def is_grace_note(note):
  """Check if a note is a grace note using multiple methods"""
  # Method 1: Check duration.isGrace property
  try:
    if hasattr(note.duration, 'isGrace') and note.duration.isGrace:
      return True
  except:
    pass
  
  # Method 2: Check if duration is zero (common for grace notes)
  try:
    if note.duration.quarterLength == 0.0:
      return True
  except:
    pass
  
  # Method 3: Check for grace container
  try:
    if hasattr(note, 'getGrace') and note.getGrace():
      return True
  except:
    pass
  
  # Method 4: Check duration type
  try:
    if hasattr(note.duration, 'type') and 'grace' in str(note.duration.type).lower():
      return True
  except:
    pass
  
  # Method 5: Check if note is in a grace container
  try:
    for context in note.contextSites():
      if 'Grace' in str(type(context)):
        return True
  except:
    pass
  
  return False


def diagnose_semitone_errors(file1, file2):
  """Detailed analysis of ±1 semitone pitch errors"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== SEMITONE ERROR ANALYSIS ===")
  
  # Get notes with their musical context
  notes1 = list(score1.flatten().notes)
  notes2 = list(score2.flatten().notes)

  if len(notes1) != len(notes2):
    print(f"⚠️  Note count mismatch: {len(notes1)} vs {len(notes2)}")
    return
  
  semitone_errors = []
  plus_one_errors = []
  minus_one_errors = []
  
  # Analyze each note
  for i, (n1, n2) in enumerate(zip(notes1, notes2)):
    if not (hasattr(n1, 'pitch') and hasattr(n2, 'pitch')):
      continue
      
    diff = n2.pitch.midi - n1.pitch.midi
    
    if diff == 1:
      plus_one_errors.append(i)
      semitone_errors.append({
        'index': i,
        'type': '+1',
        'original': n1,
        'decoded': n2,
        'context': get_note_context(score1, n1),
        'measure': get_measure_number(score1, n1)
      })
    elif diff == -1:
      minus_one_errors.append(i)
      semitone_errors.append({
        'index': i,
        'type': '-1',
        'original': n1,
        'decoded': n2,
        'context': get_note_context(score1, n1),
        'measure': get_measure_number(score1, n1)
      })
  
  print(f"Total semitone errors: {len(semitone_errors)}")
  print(f"  +1 semitone errors: {len(plus_one_errors)}")
  print(f"  -1 semitone errors: {len(minus_one_errors)}")
  
  if not semitone_errors:
    print("✅ No semitone errors found!")
    return
  
  # Pattern analysis
  analyze_semitone_patterns(semitone_errors, score1)
  
  # Show detailed examples
  print(f"\n=== DETAILED EXAMPLES (first 10) ===")
  for error in semitone_errors[:10]:
    show_semitone_error_detail(error)
  
  return semitone_errors


def get_note_context(score, note):
  """Get key signature and accidental context for a note"""
  # Find the key signature at this point
  offset = note.offset
  key_sigs = score.flat.getElementsByClass('KeySignature')
  current_key = None
  
  for ks in key_sigs:
    if ks.offset <= offset:
      current_key = ks
    else:
      break
  
  return {
    'key_signature': str(current_key) if current_key else 'C major',
    'has_accidental': note.pitch.accidental is not None,
    'accidental': str(note.pitch.accidental) if note.pitch.accidental else None,
    'pitch_class': note.pitch.pitchClass,
    'step': note.pitch.step,
    'is_grace_note': is_grace_note(note),
  }


def get_measure_number(score, note):
  try:
    if hasattr(note, 'measureNumber') and note.measureNumber:
      return note.measureNumber
  except:
    pass
  
  try:
    measures = score.parts[0].getElementsByClass('Measure')
    note_offset = note.offset
    
    for i, measure in enumerate(measures):
      measure_start = measure.offset
      measure_end = measure_start + measure.duration.quarterLength
      
      if measure_start <= note_offset < measure_end:
        return measure.number if hasattr(measure, 'number') and measure.number else i + 1
  except:
    pass
  
  try:
    flat_with_measures = score.flat
    measures_in_flat = flat_with_measures.getElementsByClass('Measure')
    
    current_measure = 1
    for element in flat_with_measures:
      if isinstance(element, music21.stream.Measure):
        current_measure = element.number if hasattr(element, 'number') and element.number else current_measure
      elif element is note:
        return current_measure
        
  except:
    pass
  
  try:
    # Assume 4/4 time signature if not found
    time_sigs = score.flat.getElementsByClass('TimeSignature')
    beats_per_measure = 4.0
    if time_sigs:
      ts = time_sigs[0]
      beats_per_measure = float(ts.numerator) * (4.0 / ts.denominator)
    
    estimated_measure = int(note.offset / beats_per_measure) + 1
    return estimated_measure
  except:
    pass
  
  return "Unknown"


def analyze_semitone_patterns(errors, score):
  """Analyze patterns in semitone errors"""
  print(f"\n=== PATTERN ANALYSIS ===")
  
  # 1. Direction bias
  plus_ones = [e for e in errors if e['type'] == '+1']
  minus_ones = [e for e in errors if e['type'] == '-1']
  
  if len(plus_ones) > len(minus_ones) * 3:
    print("🔍 Pattern: Mostly +1 errors → Your decoder adds sharps or removes flats")
  elif len(minus_ones) > len(plus_ones) * 3:
    print("🔍 Pattern: Mostly -1 errors → Your decoder adds flats or removes sharps")
  else:
    print("🔍 Pattern: Mixed +1/-1 errors → Inconsistent accidental handling")
  
  # 2. Accidental correlation
  original_with_acc = [e for e in errors if e['context']['has_accidental']]
  original_without_acc = [e for e in errors if not e['context']['has_accidental']]
  
  print(f"  Errors on notes WITH accidentals: {len(original_with_acc)}/{len(errors)}")
  print(f"  Errors on notes WITHOUT accidentals: {len(original_without_acc)}/{len(errors)}")
  
  if len(original_with_acc) > len(original_without_acc) * 2:
    print("  💡 Most errors are on notes with accidentals → Accidental encoding issue")
  elif len(original_without_acc) > len(original_with_acc) * 2:
    print("  💡 Most errors are on naturals → Key signature context issue")
  
  # 3. Key signature correlation
  key_contexts = {}
  for error in errors:
    key = error['context']['key_signature']
    key_contexts[key] = key_contexts.get(key, 0) + 1
  
  print(f"  Errors by key signature:")
  for key, count in sorted(key_contexts.items(), key=lambda x: x[1], reverse=True):
    print(f"    {key}: {count} errors")
  
  # 4. Pitch class analysis
  pitch_classes = {}
  for error in errors:
    pc = error['context']['step']
    pitch_classes[pc] = pitch_classes.get(pc, 0) + 1
  
  print(f"  Most affected note names:")
  for pc, count in sorted(pitch_classes.items(), key=lambda x: x[1], reverse=True)[:5]:
    print(f"    {pc}: {count} errors")


def show_semitone_error_detail(error):
  """Show detailed information about a specific semitone error"""
  orig = error['original']
  dec = error['decoded']
  ctx = error['context']
  
  print(f"\nNote {error['index']} (Measure {error['measure']}):")
  print(f"  Is grace?: {ctx['is_grace_note']}")
  print(f"  Original: {orig.pitch.name} (MIDI {orig.pitch.midi})")
  print(f"  Decoded:  {dec.pitch.name} (MIDI {dec.pitch.midi})")
  print(f"  Error:    {error['type']} semitone")
  print(f"  Key:      {ctx['key_signature']}")
  print(f"  Original accidental: {ctx['accidental'] or 'None'}")
  
  # Try to get decoded accidental
  dec_acc = str(dec.pitch.accidental) if dec.pitch.accidental else 'None'
  print(f"  Decoded accidental:  {dec_acc}")


# Usage function with specific recommendations
def pinpoint_semitone_issues(original_file, decoded_file):
  """Main function to pinpoint semitone issues"""
  errors = diagnose_semitone_errors(original_file, decoded_file)
  
  if not errors:
    return
  
  print(f"\n=== RECOMMENDATIONS ===")
  
  # Count error types
  plus_ones = len([e for e in errors if e['type'] == '+1'])
  minus_ones = len([e for e in errors if e['type'] == '-1'])
  with_acc = len([e for e in errors if e['context']['has_accidental']])
  without_acc = len([e for e in errors if not e['context']['has_accidental']])
  
  if plus_ones > minus_ones * 2:
    print("🎯 Focus on: Your encoding is losing flats or adding sharps")
    print("   Check: How you handle ♭ symbols and key signature flats")
  elif minus_ones > plus_ones * 2:
    print("🎯 Focus on: Your encoding is losing sharps or adding flats")
    print("   Check: How you handle ♯ symbols and key signature sharps")
  
  if with_acc > without_acc * 2:
    print("🎯 Focus on: Explicit accidental handling in your encoding")
    print("   Check: How you encode ♯, ♭, ♮ symbols")
  elif without_acc > with_acc * 2:
    print("🎯 Focus on: Key signature context preservation")
    print("   Check: How you apply key signature alterations to notes")
  
  # Show the most problematic measures
  measures = {}
  for error in errors:
    m = error['measure']
    measures[m] = measures.get(m, 0) + 1
  
  problem_measures = sorted(measures.items(), key=lambda x: x[1], reverse=True)[:5]
  print(f"\nMost problematic measures: {[f'M{m}({c})' for m, c in problem_measures]}")


def find_missing_notes(file1, file2):
  """Find missing/extra notes, chords, and rests using sequence alignment"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  def extract_elements(score):
    elements = []
    for i, element in enumerate(score.flat.notesAndRests):
      if isinstance(element, music21.note.Rest):
        elem_info = {
          'index': i, 
          'type': 'rest', 
          'signature': f"R{element.duration.quarterLength}",
          'duration': element.duration.quarterLength, 'offset': element.offset,
          'measure': get_measure_number(score, element)
        }
      elif hasattr(element, 'pitch'):  # Single note
        elem_info = {
          'index': i, 
          'type': 'note', 
          'signature': f"N{element.pitch.midi}",
          'pitch_name': element.pitch.nameWithOctave, 
          'offset': element.offset,
          'measure': get_measure_number(score, element)
        }
      elif is_chord(element):  # Chord
        pitches = sorted([p.midi for p in element.pitches])
        elem_info = {
          'index': i, 
          'type': 'chord', 
          'signature': f"C[{','.join(map(str, pitches))}]",
          'pitches': [music21.pitch.Pitch(midi=p).nameWithOctave for p in pitches],
          'offset': element.offset, 
          'measure': get_measure_number(score, element)
        }
      else:
        continue
      elements.append(elem_info)
    return elements
  
  elements1 = extract_elements(score1)
  elements2 = extract_elements(score2)
  
  print(f"=== MISSING ELEMENTS ANALYSIS ===")
  print(f"Elements: {len(elements1)} → {len(elements2)} (diff: {len(elements1) - len(elements2):+d})")
  
  # Count by type
  types1 = {'note': 0, 'chord': 0, 'rest': 0}
  types2 = {'note': 0, 'chord': 0, 'rest': 0}
  for e in elements1: types1[e['type']] += 1
  for e in elements2: types2[e['type']] += 1
  
  print(f"Notes: {types1['note']} → {types2['note']} ({types1['note'] - types2['note']:+d})")
  print(f"Chords: {types1['chord']} → {types2['chord']} ({types1['chord'] - types2['chord']:+d})")
  print(f"Rests: {types1['rest']} → {types2['rest']} ({types1['rest'] - types2['rest']:+d})")
  
  # Sequence alignment
  seq1 = [e['signature'] for e in elements1]
  seq2 = [e['signature'] for e in elements2]
  print([
    (e['signature'], e['measure']) 
    for e in elements1 
    if e['type'] == 'chord'
  ])
  print([
    (e['signature'],e['measure'])
    for e in elements2 
    if e['type'] == 'chord'
  ])
  matcher = SequenceMatcher(None, seq1, seq2)
  
  missing_elements = []
  extra_elements = []
  
  for tag, i1, i2, j1, j2 in matcher.get_opcodes():
    if tag == 'delete':
      print(f"\nMISSING from decoded:")
      for idx in range(i1, i2):
        elem = elements1[idx]
        missing_elements.append(elem)
        if elem['type'] == 'rest':
          print(f"  Rest {elem['duration']}♩ at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'note':
          print(f"  Note {elem['pitch_name']} at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'chord':
          pitches_str = '+'.join(elem['pitches'][:3])
          if len(elem['pitches']) > 3: pitches_str += '...'
          print(f"  Chord [{pitches_str}] at M{elem['measure']} (offset {elem['offset']:.2f})")
    
    elif tag == 'insert':
      print(f"\nEXTRA in decoded:")
      for idx in range(j1, j2):
        elem = elements2[idx]
        extra_elements.append(elem)
        if elem['type'] == 'rest':
          print(f"  Rest {elem['duration']}♩ at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'note':
          print(f"  Note {elem['pitch_name']} at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'chord':
          pitches_str = '+'.join(elem['pitches'][:3])
          if len(elem['pitches']) > 3: pitches_str += '...'
          print(f"  Chord [{pitches_str}] at M{elem['measure']} (offset {elem['offset']:.2f})")
  
  # Summary
  total_issues = len(missing_elements) + len(extra_elements)
  if total_issues <= 4:
    print(f"\n✅ Small difference ({total_issues} elements) - easy to fix!")
    missing_types = [e['type'] for e in missing_elements]
    extra_types = [e['type'] for e in extra_elements]
    if 'rest' in missing_types or 'rest' in extra_types:
      print("🎯 Focus on REST encoding")
    if 'note' in missing_types or 'note' in extra_types:
      print("🎯 Focus on NOTE encoding")
    if 'chord' in missing_types or 'chord' in extra_types:
      print("🎯 Focus on CHORD encoding")
  
  return missing_elements, extra_elements


class AccidentalComparisonFunctions:
  pass

def diagnose_accidental_parsing_issues(file1, file2):
  """Diagnose accidental interpretation differences between identical-looking MusicXML files"""
  
  print("=== MUSICXML ACCIDENTAL PARSING DIAGNOSIS ===")
  
  # Parse with music21
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  notes1 = list(score1.flat.notes)
  notes2 = list(score2.flat.notes)
  
  # Also parse raw XML
  tree1 = ET.parse(file1)
  tree2 = ET.parse(file2)
  
  print(f"Music21 parsed notes: {len(notes1)} vs {len(notes2)}")
  
  # Find pitch differences
  pitch_diffs = []
  for i, (n1, n2) in enumerate(zip(notes1, notes2)):
    if hasattr(n1, 'pitch') and hasattr(n2, 'pitch'):
      if n1.pitch.midi != n2.pitch.midi:
        diff_info = {
          'index': i,
          'pitch1': n1.pitch,
          'pitch2': n2.pitch,
          'midi1': n1.pitch.midi,
          'midi2': n2.pitch.midi,
          'diff': n2.pitch.midi - n1.pitch.midi,
          'measure1': get_measure_number(score1, n1),
          'measure2': get_measure_number(score2, n2),
          'offset1': n1.offset,
          'offset2': n2.offset
        }
        pitch_diffs.append(diff_info)
  
  if not pitch_diffs:
    print("✅ No pitch differences found in music21 parsing")
    return
  
  print(f"\n🔍 Found {len(pitch_diffs)} pitch differences:")
  
  for i, diff in enumerate(pitch_diffs[:]):  # Show first 5
    print(f"\nDifference {i+1}:")
    print(f"  Note index: {diff['index']}")
    print(f"  Measure: M{diff['measure1']} vs M{diff['measure2']}")
    print(f"  Music21 interpretation: {diff['pitch1'].name}{diff['pitch1'].octave} vs {diff['pitch2'].name}{diff['pitch2'].octave}")
    print(f"  MIDI values: {diff['midi1']} vs {diff['midi2']} (diff: {diff['diff']:+d})")
    print(f"  Accidentals: {diff['pitch1'].accidental} vs {diff['pitch2'].accidental}")
  
  # Now check what's actually in the XML
  print(f"\n=== RAW XML COMPARISON ===")
  check_xml_accidentals_around_diffs(file1, file2, pitch_diffs[:])
  
  # Check for context issues
  print(f"\n=== CONTEXT ANALYSIS ===")
  analyze_accidental_context_issues(score1, score2, pitch_diffs)
  
  return pitch_diffs

def check_xml_accidentals_around_diffs(file1, file2, pitch_diffs):
  """Check what's actually written in the XML around problematic notes"""
  
  def extract_note_xml_info(filename):
    tree = ET.parse(filename)
    root = tree.getroot()
    
    notes_xml = []
    for note in root.findall('.//note'):
      pitch_elem = note.find('pitch')
      if pitch_elem is not None:
        step = pitch_elem.find('step')
        octave = pitch_elem.find('octave')
        alter = pitch_elem.find('alter')
        accidental = note.find('accidental')
        
        note_info = {
          'step': step.text if step is not None else None,
          'octave': int(octave.text) if octave is not None else None,
          'alter': int(alter.text) if alter is not None else 0,
          'accidental': accidental.text if accidental is not None else None,
          'xml_element': note
        }
        notes_xml.append(note_info)
    return notes_xml
  
  xml_notes1 = extract_note_xml_info(file1)
  xml_notes2 = extract_note_xml_info(file2)
  
  print("Raw XML comparison for problematic notes:")
  
  for diff in pitch_diffs:
    idx = diff['index']
    if idx < len(xml_notes1) and idx < len(xml_notes2):
      xml1 = xml_notes1[idx]
      xml2 = xml_notes2[idx]
      
      print(f"\nNote {idx}:")
      print(f"  File1 XML: {xml1['step']}{xml1['octave']} alter={xml1['alter']} accidental={xml1['accidental']}")
      print(f"  File2 XML: {xml2['step']}{xml2['octave']} alter={xml2['alter']} accidental={xml2['accidental']}")
      
      # Check if XML is identical but music21 interprets differently
      if (xml1['step'] == xml2['step'] and xml1['octave'] == xml2['octave'] and 
          xml1['alter'] == xml2['alter'] and xml1['accidental'] == xml2['accidental']):
        print(f"  ⚠️  XML is IDENTICAL but music21 interprets differently!")
        print(f"      This suggests a context interpretation issue")

def analyze_accidental_context_issues(score1, score2, pitch_diffs):
  """Analyze context that might cause different accidental interpretation"""
  
  # Check key signatures
  keys1 = [str(k) for k in score1.flat.getElementsByClass('KeySignature')]
  keys2 = [str(k) for k in score2.flat.getElementsByClass('KeySignature')]

  print(f"Key signatures:")
  print(f"  File1: {keys1}")
  print(f"  File2: {keys2}")

  if str(keys1) != str(keys2):
    print("  ⚠️  Key signature difference detected!")
  
  # Check for previous accidentals in the same measure
  for diff in pitch_diffs[:]:
    idx = diff['index']
    measure1 = diff['measure1']
    measure2 = diff['measure2']
    
    print(f"\nContext for note {idx} (M{measure1}):")
    
    # Get all notes in the same measure before this note
    measure_notes1 = []
    measure_notes2 = []
    
    for i, note in enumerate(score1.flat.notes):
      if i >= idx:
        break
      note_measure = get_measure_number(score1, note)
      if note_measure == measure1 and hasattr(note, 'pitch'):
        measure_notes1.append((i, note.pitch.name, note.pitch.accidental))
    
    for i, note in enumerate(score2.flat.notes):
      if i >= idx:
        break
      note_measure = get_measure_number(score2, note)
      if note_measure == measure2 and hasattr(note, 'pitch'):
        measure_notes2.append((i, note.pitch.name, note.pitch.accidental))
    
    print(f"  Previous notes in measure (File1): {measure_notes1[-3:] if measure_notes1 else 'None'}")
    print(f"  Previous notes in measure (File2): {measure_notes2[-3:] if measure_notes2 else 'None'}")

def fix_accidental_interpretation_comparison(file1, file2):
  """Compare files with normalized accidental interpretation"""
  
  print("=== NORMALIZED ACCIDENTAL COMPARISON ===")
  
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  # Method 1: Compare MIDI values only (ignoring enharmonic spelling)
  midi_seq1 = [n.pitch.midi for n in score1.flat.notes if hasattr(n, 'pitch')]
  midi_seq2 = [n.pitch.midi for n in score2.flat.notes if hasattr(n, 'pitch')]
  
  print(f"MIDI sequence comparison: {'✅ IDENTICAL' if midi_seq1 == midi_seq2 else '❌ DIFFERENT'}")
  
  if midi_seq1 != midi_seq2:
    print(f"  Sequence lengths: {len(midi_seq1)} vs {len(midi_seq2)}")
    # Find first difference
    for i, (m1, m2) in enumerate(zip(midi_seq1, midi_seq2)):
      if m1 != m2:
        print(f"  First difference at note {i}: MIDI {m1} vs {m2}")
        break
  
  # Method 2: Force respelling to remove enharmonic differences
  def normalize_pitches(score):
    normalized = score.flat.stripTies()
    for note in normalized.notes:
      if hasattr(note, 'pitch'):
        # Force to sharp-based spelling
        note.pitch = note.pitch.getEnharmonic()
    return normalized
  
  try:
    norm1 = normalize_pitches(score1)
    norm2 = normalize_pitches(score2)
    
    norm_midi1 = [n.pitch.midi for n in norm1.notes if hasattr(n, 'pitch')]
    norm_midi2 = [n.pitch.midi for n in norm2.notes if hasattr(n, 'pitch')]
    
    print(f"Normalized comparison: {'✅ IDENTICAL' if norm_midi1 == norm_midi2 else '❌ DIFFERENT'}")
    
  except Exception as e:
    print(f"Normalization failed: {e}")
  
  return midi_seq1 == midi_seq2

def quick_accidental_fix_check(file1, file2):
  """Quick check to see if accidental issues are the only problem"""
  
  # Parse and compare just MIDI values
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  midi1 = [n.pitch.midi for n in score1.flat.notes if hasattr(n, 'pitch')]
  midi2 = [n.pitch.midi for n in score2.flat.notes if hasattr(n, 'pitch')]
  
  if midi1 == midi2:
    print("✅ MIDI sequences are identical - issue is only accidental display/interpretation")
    print("   Your encoding/decoding is musically correct!")
    return True
  else:
    print("❌ MIDI sequences differ - there are actual pitch errors")
    print(f"   Length: {len(midi1)} vs {len(midi2)}")
    if len(midi1) == len(midi2):
      diffs = sum(1 for m1, m2 in zip(midi1, midi2) if m1 != m2)
      print(f"   {diffs} actual pitch differences found")
    return False

# Usage functions
def comprehensive_accidental_diagnosis(file1, file2):
  """Complete accidental diagnosis"""
  print("=" * 60)
  print("MUSICXML ACCIDENTAL PARSING DIAGNOSIS")
  print("=" * 60)
  
  # Quick check first
  if quick_accidental_fix_check(file1, file2):
    print("\n🎯 RECOMMENDATION: Ignore accidental display differences")
    print("   Your encoding preserves the musical content correctly")
    return True
  
  # Detailed diagnosis
  print("\n" + "="*40)
  pitch_diffs = diagnose_accidental_parsing_issues(file1, file2)
  
  print("\n" + "="*40)
  fix_accidental_interpretation_comparison(file1, file2)
  
  return False


def compare_key_signatures_then_transpose_to_c(file1, file2):
  """Compare key signatures separately, then compare notes transposed to C major"""
  
  print("=== STEP 1: KEY SIGNATURE COMPARISON ===")
  
  # Extract key signatures from both files
  def extract_key_signatures_xml(filename):
    tree = ET.parse(filename)
    root = tree.getroot()
    
    key_sigs = []
    for part in root.findall('.//part'):
      part_id = part.get('id', 'unknown')
      for i, measure in enumerate(part.findall('measure')):
        measure_num = measure.get('number', str(i+1))
        for attributes in measure.findall('attributes'):
          key_elem = attributes.find('key')
          if key_elem is not None:
            fifths_elem = key_elem.find('fifths')
            mode_elem = key_elem.find('mode')
            
            fifths = int(fifths_elem.text) if fifths_elem is not None else 0
            mode = mode_elem.text if mode_elem is not None else 'major'
            
            key_sigs.append({
              'part': part_id,
              'measure': measure_num,
              'fifths': fifths,
              'mode': mode
            })
    return key_sigs
  
  keys1 = extract_key_signatures_xml(file1)
  keys2 = extract_key_signatures_xml(file2)
  
  print(f"Key signature count: {len(keys1)} vs {len(keys2)}")
  
  # Compare key signatures
  key_sigs_match = True
  if len(keys1) != len(keys2):
    key_sigs_match = False
    print("❌ Key signature count differs")
  else:
    for i, (k1, k2) in enumerate(zip(keys1, keys2)):
      if k1['fifths'] != k2['fifths'] or k1['mode'] != k2['mode']:
        key_sigs_match = False
        print(f"❌ Key {i+1}: Part {k1['part']} M{k1['measure']} - "
              f"fifths {k1['fifths']} vs {k2['fifths']}, mode {k1['mode']} vs {k2['mode']}")
  
  if key_sigs_match:
    print("✅ Key signatures match perfectly")
  
  print(f"\n=== STEP 2: TRANSPOSE BOTH TO C MAJOR AND COMPARE ===")
  
  # Create C major versions
  c_major_file1 = file1.parent / file1.name.replace('.musicxml', '_c_major.musicxml')
  c_major_file2 = file2.parent / file2.name.replace('.musicxml', '_c_major.musicxml')
  
  remove_all_key_signatures(file1, c_major_file1)
  remove_all_key_signatures(file2, c_major_file2)
  
  # Compare the C major versions
  score1_c = music21.converter.parse(c_major_file1)
  score2_c = music21.converter.parse(c_major_file2)
  
  # Extract MIDI sequences from C major versions
  midi1 = []
  midi2 = []
  
  for element in score1_c.flat.notes:
    if hasattr(element, 'pitch'):
      midi1.append(element.pitch.midi)
    elif is_chord(element):
      for pitch in element.pitches:
        midi1.append(pitch.midi)
  
  for element in score2_c.flat.notes:
    if hasattr(element, 'pitch'):
      midi2.append(element.pitch.midi)
    elif is_chord(element):
      for pitch in element.pitches:
        midi2.append(pitch.midi)
  
  print(f"C major note count: {len(midi1)} vs {len(midi2)}")
  
  notes_match = midi1 == midi2
  
  if notes_match:
    print("✅ Notes match perfectly when transposed to C major")
  else:
    print("❌ Notes differ even in C major")
    if len(midi1) == len(midi2):
      diffs = sum(1 for m1, m2 in zip(midi1, midi2) if m1 != m2)
      print(f"   {diffs} pitch differences found")
      
      # Show first few differences
      for i, (m1, m2) in enumerate(zip(midi1, midi2)):
        if m1 != m2:
          note1_name = music21.pitch.Pitch(midi=m1).nameWithOctave
          note2_name = music21.pitch.Pitch(midi=m2).nameWithOctave
          print(f"   Note {i}: {note1_name} (MIDI {m1}) vs {note2_name} (MIDI {m2})")
    else:
      print(f"   Different note counts: {len(midi1)} vs {len(midi2)}")
  
  # Summary
  print(f"\n=== SUMMARY ===")
  if key_sigs_match and notes_match:
    print("✅ PERFECT MATCH: Both key signatures and notes are identical")
  elif key_sigs_match and not notes_match:
    print("🎯 Key signatures match, notes differ")
    print("   → Focus on note encoding logic")
  elif not key_sigs_match and notes_match:
    print("🎯 Notes match, key signatures differ")  
    print("   → Focus on key signature encoding logic")
  else:
    print("❌ Both key signatures and notes differ")
  
  return key_sigs_match, notes_match


def remove_all_key_signatures(input_file, output_file):
  """Remove all key signature elements from MusicXML file"""
  
  tree = ET.parse(input_file)
  root = tree.getroot()
  
  removed_count = 0
  
  # Remove all <key> elements
  for part in root.findall('.//part'):
    for measure in part.findall('measure'):
      for attributes in measure.findall('attributes'):
        key_elem = attributes.find('key')
        if key_elem is not None:
          attributes.remove(key_elem)
          removed_count += 1
          
          # Remove empty attributes elements
          if len(list(attributes)) == 0:
            measure.remove(attributes)
  
  # Save the modified file
  tree.write(output_file, encoding='utf-8', xml_declaration=True)
  print(f"Removed {removed_count} key signatures, saved as {output_file}")
  
  return removed_count


def compare_with_key_normalization(file1, file2):
  """Quick comparison with key signature normalization"""
  
  print("=== KEY SIGNATURE NORMALIZED COMPARISON ===")
  
  # Step 1: Quick key signature check
  def get_key_signature_sequence(filename):
    tree = ET.parse(filename)
    keys = []
    for key_elem in tree.findall('.//key'):
      fifths = key_elem.find('fifths')
      keys.append(
        int(fifths.text) if fifths is not None else 0,
      )
    return keys
  
  keys1 = get_key_signature_sequence(file1)
  keys2 = get_key_signature_sequence(file2)
  
  print(f"Key signatures: {keys1}")
  print(f"                {keys2}")
  print(f"Key sigs match: {'✅' if keys1 == keys2 else '❌'}")
  
  # Step 2: Compare with keys removed
  temp_file1 = 'temp_no_keys_1.xml'
  temp_file2 = 'temp_no_keys_2.xml'
  
  remove_all_key_signatures(file1, temp_file1)
  remove_all_key_signatures(file2, temp_file2)
  
  # Parse and compare
  score1 = music21.converter.parse(temp_file1)
  score2 = music21.converter.parse(temp_file2)
  
  midi1 = [n.pitch.midi for n in score1.flat.notes if hasattr(n, 'pitch')]
  midi2 = [n.pitch.midi for n in score2.flat.notes if hasattr(n, 'pitch')]
  
  # Add chord notes
  for element in score1.flat.notes:
    if is_chord(element):
      midi1.extend([p.midi for p in element.pitches])
  
  for element in score2.flat.notes:
    if is_chord(element):
      midi2.extend([p.midi for p in element.pitches])
  
  notes_match = midi1 == midi2
  print(f"Notes match (no key sigs): {'✅' if notes_match else '❌'}")
  
  if not notes_match and len(midi1) == len(midi2):
    diffs = sum(1 for m1, m2 in zip(midi1, midi2) if m1 != m2)
    print(f"   {diffs} note differences found")
    for m1, m2, is_same in [(m1, m2, m1==m2) for m1, m2 in zip(midi1, midi2)]:
      print(m1, m2, is_same)
  
  # Clean up temp files
  import os
  try:
    os.remove(temp_file1)
    os.remove(temp_file2)
  except:
    pass
  
  return keys1 == keys2, notes_match



class ChordComparisonFunctions:
  pass


def get_chord_info(element):
  """Get detailed chord information"""
  if is_chord(element):
    return {
      'type': 'chord',
      'pitches': tuple(sorted([p.midi for p in element.pitches])),
      'pitch_names': tuple(sorted([p.name for p in element.pitches])),
      'note_count': len(element.pitches),
      'root': element.root().name if len(element.pitches) > 0 else None,
      'bass': element.bass().name if len(element.pitches) > 0 else None,
      'duration': element.duration.quarterLength,
      'offset': element.offset,
      'is_grace': is_grace_note(element)
    }
  elif hasattr(element, 'pitch'):  # Single note
    return {
      'type': 'note',
      'pitches': (element.pitch.midi,),
      'pitch_names': (element.pitch.name,),
      'note_count': 1,
      'root': element.pitch.name,
      'bass': element.pitch.name,
      'duration': element.duration.quarterLength,
      'offset': element.offset,
      'is_grace': is_grace_note(element)
    }
  else:
    return None


def compare_chord_structures(chord1, chord2):
  """Compare two chord structures and identify differences"""
  info1 = get_chord_info(chord1)
  info2 = get_chord_info(chord2)
  
  if not info1 or not info2:
    return None
  
  differences = []
  
  # Type change (note ↔ chord)
  if info1['type'] != info2['type']:
    differences.append(f"Type change: {info1['type']} → {info2['type']}")
  
  # Note count change
  if info1['note_count'] != info2['note_count']:
    differences.append(f"Note count: {info1['note_count']} → {info2['note_count']}")
  
  # Pitch changes
  pitches1 = set(info1['pitches'])
  pitches2 = set(info2['pitches'])
  
  added_pitches = pitches2 - pitches1
  removed_pitches = pitches1 - pitches2
  
  if added_pitches:
    added_names = [music21.pitch.Pitch(midi=p).name for p in added_pitches]
    differences.append(f"Added pitches: {added_names}")
  
  if removed_pitches:
    removed_names = [music21.pitch.Pitch(midi=p).name for p in removed_pitches]
    differences.append(f"Removed pitches: {removed_names}")
  
  return {
    'identical': len(differences) == 0,
    'differences': differences,
    'info1': info1,
    'info2': info2
  }


def diagnose_chord_differences(file1, file2):
  """Comprehensive chord difference analysis"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== CHORD STRUCTURE ANALYSIS ===")
  
  elements1 = list(score1.flat.notesAndRests)
  elements2 = list(score2.flat.notesAndRests)
  
  # Filter to notes and chords only
  musical_elements1 = [e for e in elements1 if hasattr(e, 'pitch') or is_chord(e)]
  musical_elements2 = [e for e in elements2 if hasattr(e, 'pitch') or is_chord(e)]
  
  if len(musical_elements1) != len(musical_elements2):
    print(f"⚠️  Musical element count mismatch: {len(musical_elements1)} vs {len(musical_elements2)}")
    return
  
  # Count chord vs note types
  chords1 = [e for e in musical_elements1 if is_chord(e)]
  notes1 = [e for e in musical_elements1 if hasattr(e, 'pitch') and not is_chord(e)]
  chords2 = [e for e in musical_elements2 if is_chord(e)]
  notes2 = [e for e in musical_elements2 if hasattr(e, 'pitch') and not is_chord(e)]
  
  print(f"Original: {len(chords1)} chords, {len(notes1)} single notes")
  print(f"Decoded:  {len(chords2)} chords, {len(notes2)} single notes")
  
  chord_differences = []
  type_changes = []
  pitch_changes = []
  
  for i, (e1, e2) in enumerate(zip(musical_elements1, musical_elements2)):
    comparison = compare_chord_structures(e1, e2)
    
    if comparison and not comparison['identical']:
      measure1 = get_measure_number(score1, e1)
      measure2 = get_measure_number(score2, e2)
      
      chord_differences.append({
        'index': i,
        'comparison': comparison,
        'measure1': measure1,
        'measure2': measure2
      })

      # Categorize the type of difference
      if any('Type change' in diff for diff in comparison['differences']):
        type_changes.append(i)
      if any('pitches' in diff for diff in comparison['differences']):
        pitch_changes.append(i)
  
  print(f"\nChord structure differences: {len(chord_differences)}")
  print(f"  Type changes (note ↔ chord): {len(type_changes)}")
  print(f"  Pitch content changes: {len(pitch_changes)}")
  
  # Show detailed examples
  print(f"\n=== DETAILED CHORD DIFFERENCES (first 10) ===")
  for i, diff in enumerate(chord_differences[:10]):
    idx = diff['index']
    comp = diff['comparison']
    info1 = comp['info1']
    info2 = comp['info2']
    
    print(f"\nElement {idx} in Measure {diff['measure1']}:")
    print(f"  Original: {info1['type']} - {info1['pitch_names']} ({info1['note_count']} notes)")
    print(f"  Decoded:  {info2['type']} - {info2['pitch_names']} ({info2['note_count']} notes)")
    print(f"  Changes: {'; '.join(comp['differences'])}")
  
  return chord_differences


def analyze_chord_patterns(file1, file2):
  """Analyze patterns in chord encoding/decoding"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  elements1 = [e for e in score1.flat.notesAndRests if hasattr(e, 'pitch') or is_chord(e)]
  elements2 = [e for e in score2.flat.notesAndRests if hasattr(e, 'pitch') or is_chord(e)]
  
  # Pattern analysis
  note_to_chord = 0  # Single note became chord
  chord_to_note = 0  # Chord became single note
  chord_size_changes = []
  
  for e1, e2 in zip(elements1, elements2):
    info1 = get_chord_info(e1)
    info2 = get_chord_info(e2)
    
    if info1 and info2:
      if info1['type'] == 'note' and info2['type'] == 'chord':
        note_to_chord += 1
      elif info1['type'] == 'chord' and info2['type'] == 'note':
        chord_to_note += 1
      elif info1['type'] == 'chord' and info2['type'] == 'chord':
        if info1['note_count'] != info2['note_count']:
          chord_size_changes.append((info1['note_count'], info2['note_count']))
  
  print("=== CHORD PATTERN ANALYSIS ===")
  print(f"Single notes converted to chords: {note_to_chord}")
  print(f"Chords converted to single notes: {chord_to_note}")
  print(f"Chord size changes: {len(chord_size_changes)}")
  
  if chord_size_changes:
    print("Chord size change patterns:")
    size_change_counts = {}
    for old, new in chord_size_changes:
      change = f"{old}→{new}"
      size_change_counts[change] = size_change_counts.get(change, 0) + 1
    
    for change, count in sorted(size_change_counts.items(), key=lambda x: x[1], reverse=True):
      print(f"  {change} notes: {count} times")



class OffsetComparisonFunctions:
  pass


def compare_offsets(file1, file2, tolerance=0.001):
  """Comprehensive offset/timing comparison"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== OFFSET/TIMING ANALYSIS ===")
  
  elements1 = list(score1.flat.notesAndRests)
  elements2 = list(score2.flat.notesAndRests)
  
  # musical_elements1 = [e for e in elements1 if hasattr(e, 'pitch') or is_chord(e)]
  # musical_elements2 = [e for e in elements2 if hasattr(e, 'pitch') or is_chord(e)]
  musical_elements1 = elements1
  musical_elements2 = elements2
  
  if len(musical_elements1) != len(musical_elements2):
    print(f"⚠️  Element count mismatch: {len(musical_elements1)} vs {len(musical_elements2)}")
    return
  
  offset_differences = []
  duration_differences = []
  timing_shifts = []
  
  for i, (e1, e2) in enumerate(zip(musical_elements1, musical_elements2)):
    offset_diff = e2.offset - e1.offset
    duration_diff = e2.duration.quarterLength - e1.duration.quarterLength
    measure_number = get_measure_number(score1, e1)
    
    if abs(offset_diff) > tolerance:
      offset_differences.append({
        'index': i,
        'original_offset': float(e1.offset),
        'decoded_offset': float(e2.offset),
        'difference': float(offset_diff),
        'element_type': 'chord' if is_chord(e1) else 'note',
        'pitch_info': get_chord_info(e1)['pitch_names'] if get_chord_info(e1) else None,
        'measure': measure_number,
      })
      timing_shifts.append(offset_diff)
    
    if abs(duration_diff) > tolerance:
      duration_differences.append({
        'index': i,
        'original_duration': e1.duration.quarterLength,
        'decoded_duration': e2.duration.quarterLength,
        'difference': duration_diff,
        'element_type': 'chord' if is_chord(e1) else 'note',
        'measure': measure_number,
      })
  
  print(f"Offset differences (>{tolerance}): {len(offset_differences)}")
  print(f"Duration differences (>{tolerance}): {len(duration_differences)}")
  
  # Analyze timing shift patterns
  if timing_shifts:
    print(f"\n=== TIMING SHIFT ANALYSIS ===")
    avg_shift = sum(timing_shifts) / len(timing_shifts)
    print(f"Average timing shift: {avg_shift:.6f} quarter notes")
    
    # Check for systematic shift
    if abs(avg_shift) > tolerance:
      if avg_shift > 0:
        print(f"  → Systematic delay: decoded notes are {avg_shift:.6f} quarter notes later")
      else:
        print(f"  → Systematic advance: decoded notes are {abs(avg_shift):.6f} quarter notes earlier")
    
    # Check for consistent shifts
    unique_shifts = list(set(round(shift, 6) for shift in timing_shifts))
    if len(unique_shifts) == 1:
      print(f"  → All shifts are identical: {unique_shifts[0]:.6f}")
    elif len(unique_shifts) <= 3:
      print(f"  → Limited shift values: {unique_shifts}")
    else:
      print(f"  → Variable shifts: {len(unique_shifts)} different values")
  
  # Show detailed examples
  print(f"\n=== DETAILED OFFSET DIFFERENCES (first 10) ===")
  for i, diff in enumerate(offset_differences[:10]):
    idx = diff['index']
    print(f"Element {idx} ({diff['element_type']}) in Measure {diff['measure']}:")
    print(f"  Pitches: {diff['pitch_info']}")
    print(f"  Offset: {diff['original_offset']:.6f} → {diff['decoded_offset']:.6f}")
    print(f"  Difference: {diff['difference']:+.6f} quarter notes")
    
    # Convert to musical terms
    if abs(diff['difference']) >= 1.0:
      beats = abs(diff['difference'])
      print(f"  = {beats:.2f} beats {'later' if diff['difference'] > 0 else 'earlier'}")
    elif abs(diff['difference']) >= 0.5:
      print(f"  = ~half beat {'later' if diff['difference'] > 0 else 'earlier'}")
    elif abs(diff['difference']) >= 0.25:
      print(f"  = ~quarter beat {'later' if diff['difference'] > 0 else 'earlier'}")
  
  print(f"\n=== DETAILED DURATION DIFFERENCES (first 10) ===")
  for i, diff in enumerate(duration_differences[:10]):
    idx = diff['index']
    print(f"Element {idx} ({diff['element_type']}) in Measure {diff['measure']}:")
    print(f"  Duration: {diff['original_duration']:.6f} → {diff['decoded_duration']:.6f}")
    print(f"  Difference: {diff['difference']:+.6f} quarter notes")
  
  return offset_differences, duration_differences


def analyze_rhythmic_patterns(file1, file2):
  """Analyze rhythmic pattern preservation"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== RHYTHMIC PATTERN ANALYSIS ===")
  
  elements1 = [e for e in score1.flat.notesAndRests if hasattr(e, 'duration')]
  elements2 = [e for e in score2.flat.notesAndRests if hasattr(e, 'duration')]
  
  # Extract rhythm patterns
  durations1 = [e.duration.quarterLength for e in elements1]
  durations2 = [e.duration.quarterLength for e in elements2]
  
  # Find common duration values
  unique_durations1 = set(durations1)
  unique_durations2 = set(durations2)
  
  print(f"Original duration types: {len(unique_durations1)}")
  print(f"Decoded duration types: {len(unique_durations2)}")
  
  # Common duration names
  duration_names = {
    4.0: "whole", 2.0: "half", 1.0: "quarter", 0.5: "eighth", 
    0.25: "sixteenth", 0.125: "thirty-second", 1.5: "dotted half",
    0.75: "dotted quarter", 0.375: "dotted eighth", 3.0: "dotted whole"
  }
  
  print(f"\nOriginal durations:")
  for dur in sorted(unique_durations1):
    count = durations1.count(dur)
    name = duration_names.get(dur, f"{dur} quarters")
    print(f"  {name}: {count} times")
  
  print(f"\nDecoded durations:")
  for dur in sorted(unique_durations2):
    count = durations2.count(dur)
    name = duration_names.get(dur, f"{dur} quarters")
    print(f"  {name}: {count} times")
  
  # Check for duration quantization issues
  lost_durations = unique_durations1 - unique_durations2
  gained_durations = unique_durations2 - unique_durations1
  
  if lost_durations:
    print(f"\nLost duration types:")
    for dur in sorted(lost_durations):
      name = duration_names.get(dur, f"{dur} quarters")
      print(f"  {name}")
  
  if gained_durations:
    print(f"\nGained duration types:")
    for dur in sorted(gained_durations):
      name = duration_names.get(dur, f"{dur} quarters")
      print(f"  {name}")


def comprehensive_timing_analysis(file1, file2, tolerance=0.001):
  """Combined analysis of all timing-related issues"""
  print("=== COMPREHENSIVE TIMING ANALYSIS ===")
  
  # 1. Basic offset comparison
  offset_diffs, duration_diffs = compare_offsets(file1, file2, tolerance=tolerance)
  
  print(f"\n")
  
  # 2. Rhythmic pattern analysis
  analyze_rhythmic_patterns(file1, file2)


