from pathlib import Path
import shutil
from itertools import groupby

import xml
import xml.etree.ElementTree as ET

import music21
from difflib import SequenceMatcher


def strip_invisible_elements(tree:ET.ElementTree, remove_position_modifications=False) -> ET.ElementTree:
  """
  remove all <El print-object="no"/>
  using etree
  """
  root = tree.getroot()

  for measure in reversed(root.findall('.//measure')):
    for el in reversed(measure.findall('.//note[@print-object="no"]')):
      measure.remove(el)
  
    if remove_position_modifications:
      for el in reversed(measure.findall('.//backup')):
        measure.remove(el)
      for el in reversed(measure.findall('.//forward')):
        measure.remove(el)

  return ET.ElementTree(root)

"""
Most of the Diagnose functions are generated by Claude Sonnet 4
"""
class DiagnoseFunctions:
  pass


def remove_consecutive_items(seq):
  return [key for key, _ in groupby(seq)]



def is_chord(element):
  """Check if element is a chord"""
  return isinstance(element, music21.chord.Chord)


def compare_note_sequences(file1, file2, tolerance=0.01):
  """Direct comparison of note sequences without MIDI conversion"""
  try:
    score1 = music21.converter.parse(file1)
  except:
    parser = music21.musicxml.xmlToM21.MusicXMLImporter()
    score1 = parser.scoreFromFile(file1)
  
  try:
    score2 = music21.converter.parse(file2)
  except:
    parser = music21.musicxml.xmlToM21.MusicXMLImporter()
    score2 = parser.scoreFromFile(file2)

  def extract_note_data(score):
    """Extract normalized note data from score"""
    notes_data = []
    
    for element in score.flatten().notesAndRests:
      if isinstance(element, music21.note.Note):
        notes_data.append({
          'type': 'note',
          'pitch': element.pitch.midi,
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
      elif isinstance(element, music21.chord.Chord):
        notes_data.append({
          'type': 'chord',
          'pitches': tuple(sorted(p.midi for p in element.pitches)),
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
      elif isinstance(element, music21.note.Rest):
        notes_data.append({
          'type': 'rest',
          'offset': float(element.offset),
          'duration': float(element.duration.quarterLength)
        })
    
    return notes_data
  
  notes1 = extract_note_data(score1)
  notes2 = extract_note_data(score2)
  
  if len(notes1) != len(notes2):
    return False, f"Note count differs: {len(notes1)} vs {len(notes2)}"
  
  # Compare note by note with tolerance for floating point
  for i, (n1, n2) in enumerate(zip(notes1, notes2)):
    if n1['type'] != n2['type']:
      return False, f"Note {i}: type differs {n1['type']} vs {n2['type']}"
    
    if abs(n1['offset'] - n2['offset']) > tolerance:
      return False, f"Note {i}: offset differs {n1['offset']} vs {n2['offset']}"
    
    if abs(n1['duration'] - n2['duration']) > tolerance:
      return False, f"Note {i}: duration differs {n1['duration']} vs {n2['duration']}"
    
    if n1['type'] == 'note' and n1['pitch'] != n2['pitch']:
      return False, f"Note {i}: pitch differs {n1['pitch']} vs {n2['pitch']}"
    
    if n1['type'] == 'chord' and n1['pitches'] != n2['pitches']:
      return False, f"Chord {i}: pitches differ {n1['pitches']} vs {n2['pitches']}"
  
  return True, "Files are identical"


class NoteComparisonFunctions:
  pass


def is_grace_note(note):
  """Check if a note is a grace note using multiple methods"""
  # Method 1: Check duration.isGrace property
  try:
    if hasattr(note.duration, 'isGrace') and note.duration.isGrace:
      return True
  except:
    pass
  
  # Method 2: Check if duration is zero (common for grace notes)
  try:
    if note.duration.quarterLength == 0.0:
      return True
  except:
    pass
  
  # Method 3: Check for grace container
  try:
    if hasattr(note, 'getGrace') and note.getGrace():
      return True
  except:
    pass
  
  # Method 4: Check duration type
  try:
    if hasattr(note.duration, 'type') and 'grace' in str(note.duration.type).lower():
      return True
  except:
    pass
  
  # Method 5: Check if note is in a grace container
  try:
    for context in note.contextSites():
      if 'Grace' in str(type(context)):
        return True
  except:
    pass
  
  return False


def diagnose_semitone_errors(file1, file2):
  """Detailed analysis of ±1 semitone pitch errors"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== SEMITONE ERROR ANALYSIS ===")
  
  # Get notes with their musical context
  notes1 = list(score1.flatten().notes)
  notes2 = list(score2.flatten().notes)

  if len(notes1) != len(notes2):
    print(f"⚠️  Note count mismatch: {len(notes1)} vs {len(notes2)}")
    return
  
  semitone_errors = []
  plus_one_errors = []
  minus_one_errors = []
  
  # Analyze each note
  for i, (n1, n2) in enumerate(zip(notes1, notes2)):
    if not (hasattr(n1, 'pitch') and hasattr(n2, 'pitch')):
      continue
      
    diff = n2.pitch.midi - n1.pitch.midi
    
    if diff == 1:
      plus_one_errors.append(i)
      semitone_errors.append({
        'index': i,
        'type': '+1',
        'original': n1,
        'decoded': n2,
        'context': get_note_context(score1, n1),
        'measure': get_measure_number(score1, n1)
      })
    elif diff == -1:
      minus_one_errors.append(i)
      semitone_errors.append({
        'index': i,
        'type': '-1',
        'original': n1,
        'decoded': n2,
        'context': get_note_context(score1, n1),
        'measure': get_measure_number(score1, n1)
      })
  
  print(f"Total semitone errors: {len(semitone_errors)}")
  print(f"  +1 semitone errors: {len(plus_one_errors)}")
  print(f"  -1 semitone errors: {len(minus_one_errors)}")
  
  if not semitone_errors:
    print("✅ No semitone errors found!")
    return
  
  # Pattern analysis
  analyze_semitone_patterns(semitone_errors, score1)
  
  # Show detailed examples
  print(f"\n=== DETAILED EXAMPLES (first 10) ===")
  for error in semitone_errors[:10]:
    show_semitone_error_detail(error)
  
  return semitone_errors


def get_note_context(score, note):
  """Get key signature and accidental context for a note"""
  # Find the key signature at this point
  offset = note.offset
  key_sigs = score.flat.getElementsByClass('KeySignature')
  current_key = None
  
  for ks in key_sigs:
    if ks.offset <= offset:
      current_key = ks
    else:
      break
  
  return {
    'key_signature': str(current_key) if current_key else 'C major',
    'has_accidental': note.pitch.accidental is not None,
    'accidental': str(note.pitch.accidental) if note.pitch.accidental else None,
    'pitch_class': note.pitch.pitchClass,
    'step': note.pitch.step,
    'is_grace_note': is_grace_note(note),
  }


def get_measure_number(score, note):
  try:
    if hasattr(note, 'measureNumber') and note.measureNumber:
      return note.measureNumber
  except:
    pass
  
  try:
    measures = score.parts[0].getElementsByClass('Measure')
    note_offset = note.offset
    
    for i, measure in enumerate(measures):
      measure_start = measure.offset
      measure_end = measure_start + measure.duration.quarterLength
      
      if measure_start <= note_offset < measure_end:
        return measure.number if hasattr(measure, 'number') and measure.number else i + 1
  except:
    pass
  
  try:
    flat_with_measures = score.flat
    measures_in_flat = flat_with_measures.getElementsByClass('Measure')
    
    current_measure = 1
    for element in flat_with_measures:
      if isinstance(element, music21.stream.Measure):
        current_measure = element.number if hasattr(element, 'number') and element.number else current_measure
      elif element is note:
        return current_measure
        
  except:
    pass
  
  try:
    # Assume 4/4 time signature if not found
    time_sigs = score.flat.getElementsByClass('TimeSignature')
    beats_per_measure = 4.0
    if time_sigs:
      ts = time_sigs[0]
      beats_per_measure = float(ts.numerator) * (4.0 / ts.denominator)
    
    estimated_measure = int(note.offset / beats_per_measure) + 1
    return estimated_measure
  except:
    pass
  
  return "Unknown"


def analyze_semitone_patterns(errors, score):
  """Analyze patterns in semitone errors"""
  print(f"\n=== PATTERN ANALYSIS ===")
  
  # 1. Direction bias
  plus_ones = [e for e in errors if e['type'] == '+1']
  minus_ones = [e for e in errors if e['type'] == '-1']
  
  if len(plus_ones) > len(minus_ones) * 3:
    print("🔍 Pattern: Mostly +1 errors → Your decoder adds sharps or removes flats")
  elif len(minus_ones) > len(plus_ones) * 3:
    print("🔍 Pattern: Mostly -1 errors → Your decoder adds flats or removes sharps")
  else:
    print("🔍 Pattern: Mixed +1/-1 errors → Inconsistent accidental handling")
  
  # 2. Accidental correlation
  original_with_acc = [e for e in errors if e['context']['has_accidental']]
  original_without_acc = [e for e in errors if not e['context']['has_accidental']]
  
  print(f"  Errors on notes WITH accidentals: {len(original_with_acc)}/{len(errors)}")
  print(f"  Errors on notes WITHOUT accidentals: {len(original_without_acc)}/{len(errors)}")
  
  if len(original_with_acc) > len(original_without_acc) * 2:
    print("  💡 Most errors are on notes with accidentals → Accidental encoding issue")
  elif len(original_without_acc) > len(original_with_acc) * 2:
    print("  💡 Most errors are on naturals → Key signature context issue")
  
  # 3. Key signature correlation
  key_contexts = {}
  for error in errors:
    key = error['context']['key_signature']
    key_contexts[key] = key_contexts.get(key, 0) + 1
  
  print(f"  Errors by key signature:")
  for key, count in sorted(key_contexts.items(), key=lambda x: x[1], reverse=True):
    print(f"    {key}: {count} errors")
  
  # 4. Pitch class analysis
  pitch_classes = {}
  for error in errors:
    pc = error['context']['step']
    pitch_classes[pc] = pitch_classes.get(pc, 0) + 1
  
  print(f"  Most affected note names:")
  for pc, count in sorted(pitch_classes.items(), key=lambda x: x[1], reverse=True)[:5]:
    print(f"    {pc}: {count} errors")


def show_semitone_error_detail(error):
  """Show detailed information about a specific semitone error"""
  orig = error['original']
  dec = error['decoded']
  ctx = error['context']
  
  print(f"\nNote {error['index']} (Measure {error['measure']}):")
  print(f"  Is grace?: {ctx['is_grace_note']}")
  print(f"  Original: {orig.pitch.name} (MIDI {orig.pitch.midi})")
  print(f"  Decoded:  {dec.pitch.name} (MIDI {dec.pitch.midi})")
  print(f"  Error:    {error['type']} semitone")
  print(f"  Key:      {ctx['key_signature']}")
  print(f"  Original accidental: {ctx['accidental'] or 'None'}")
  
  # Try to get decoded accidental
  dec_acc = str(dec.pitch.accidental) if dec.pitch.accidental else 'None'
  print(f"  Decoded accidental:  {dec_acc}")


# Usage function with specific recommendations
def pinpoint_semitone_issues(original_file, decoded_file):
  """Main function to pinpoint semitone issues"""
  errors = diagnose_semitone_errors(original_file, decoded_file)
  
  if not errors:
    return
  
  print(f"\n=== RECOMMENDATIONS ===")
  
  # Count error types
  plus_ones = len([e for e in errors if e['type'] == '+1'])
  minus_ones = len([e for e in errors if e['type'] == '-1'])
  with_acc = len([e for e in errors if e['context']['has_accidental']])
  without_acc = len([e for e in errors if not e['context']['has_accidental']])
  
  if plus_ones > minus_ones * 2:
    print("🎯 Focus on: Your encoding is losing flats or adding sharps")
    print("   Check: How you handle ♭ symbols and key signature flats")
  elif minus_ones > plus_ones * 2:
    print("🎯 Focus on: Your encoding is losing sharps or adding flats")
    print("   Check: How you handle ♯ symbols and key signature sharps")
  
  if with_acc > without_acc * 2:
    print("🎯 Focus on: Explicit accidental handling in your encoding")
    print("   Check: How you encode ♯, ♭, ♮ symbols")
  elif without_acc > with_acc * 2:
    print("🎯 Focus on: Key signature context preservation")
    print("   Check: How you apply key signature alterations to notes")
  
  # Show the most problematic measures
  measures = {}
  for error in errors:
    m = error['measure']
    measures[m] = measures.get(m, 0) + 1
  
  problem_measures = sorted(measures.items(), key=lambda x: x[1], reverse=True)[:5]
  print(f"\nMost problematic measures: {[f'M{m}({c})' for m, c in problem_measures]}")


def find_missing_notes(file1, file2):
  """Find missing/extra notes, chords, and rests using sequence alignment"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  def extract_elements(score):
    elements = []
    for i, element in enumerate(score.flat.notesAndRests):
      if isinstance(element, music21.note.Rest):
        elem_info = {
          'index': i, 
          'type': 'rest', 
          'signature': f"R{element.duration.quarterLength}",
          'duration': element.duration.quarterLength, 'offset': element.offset,
          'measure': get_measure_number(score, element)
        }
      elif hasattr(element, 'pitch'):  # Single note
        elem_info = {
          'index': i, 
          'type': 'note', 
          'signature': f"N{element.pitch.midi}",
          'pitch_name': element.pitch.nameWithOctave, 
          'offset': element.offset,
          'measure': get_measure_number(score, element)
        }
      elif is_chord(element):  # Chord
        pitches = sorted([p.midi for p in element.pitches])
        elem_info = {
          'index': i, 
          'type': 'chord', 
          'signature': f"C[{','.join(map(str, pitches))}]",
          'pitches': [music21.pitch.Pitch(midi=p).nameWithOctave for p in pitches],
          'offset': element.offset, 
          'measure': get_measure_number(score, element)
        }
      else:
        continue
      elements.append(elem_info)
    return elements
  
  elements1 = extract_elements(score1)
  elements2 = extract_elements(score2)
  
  print(f"=== MISSING ELEMENTS ANALYSIS ===")
  print(f"Elements: {len(elements1)} → {len(elements2)} (diff: {len(elements1) - len(elements2):+d})")
  
  # Count by type
  types1 = {'note': 0, 'chord': 0, 'rest': 0}
  types2 = {'note': 0, 'chord': 0, 'rest': 0}
  for e in elements1: types1[e['type']] += 1
  for e in elements2: types2[e['type']] += 1
  
  print(f"Notes: {types1['note']} → {types2['note']} ({types1['note'] - types2['note']:+d})")
  print(f"Chords: {types1['chord']} → {types2['chord']} ({types1['chord'] - types2['chord']:+d})")
  print(f"Rests: {types1['rest']} → {types2['rest']} ({types1['rest'] - types2['rest']:+d})")
  
  # Sequence alignment
  seq1 = [e['signature'] for e in elements1]
  seq2 = [e['signature'] for e in elements2]
  print([
    (e['signature'], e['measure']) 
    for e in elements1 
    if e['type'] == 'chord'
  ])
  print([
    (e['signature'],e['measure'])
    for e in elements2 
    if e['type'] == 'chord'
  ])
  matcher = SequenceMatcher(None, seq1, seq2)
  
  missing_elements = []
  extra_elements = []
  
  for tag, i1, i2, j1, j2 in matcher.get_opcodes():
    if tag == 'delete':
      print(f"\nMISSING from decoded:")
      for idx in range(i1, i2):
        elem = elements1[idx]
        missing_elements.append(elem)
        if elem['type'] == 'rest':
          print(f"  Rest {elem['duration']}♩ at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'note':
          print(f"  Note {elem['pitch_name']} at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'chord':
          pitches_str = '+'.join(elem['pitches'][:3])
          if len(elem['pitches']) > 3: pitches_str += '...'
          print(f"  Chord [{pitches_str}] at M{elem['measure']} (offset {elem['offset']:.2f})")
    
    elif tag == 'insert':
      print(f"\nEXTRA in decoded:")
      for idx in range(j1, j2):
        elem = elements2[idx]
        extra_elements.append(elem)
        if elem['type'] == 'rest':
          print(f"  Rest {elem['duration']}♩ at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'note':
          print(f"  Note {elem['pitch_name']} at M{elem['measure']} (offset {elem['offset']:.2f})")
        elif elem['type'] == 'chord':
          pitches_str = '+'.join(elem['pitches'][:3])
          if len(elem['pitches']) > 3: pitches_str += '...'
          print(f"  Chord [{pitches_str}] at M{elem['measure']} (offset {elem['offset']:.2f})")
  
  # Summary
  total_issues = len(missing_elements) + len(extra_elements)
  if total_issues <= 4:
    print(f"\n✅ Small difference ({total_issues} elements) - easy to fix!")
    missing_types = [e['type'] for e in missing_elements]
    extra_types = [e['type'] for e in extra_elements]
    if 'rest' in missing_types or 'rest' in extra_types:
      print("🎯 Focus on REST encoding")
    if 'note' in missing_types or 'note' in extra_types:
      print("🎯 Focus on NOTE encoding")
    if 'chord' in missing_types or 'chord' in extra_types:
      print("🎯 Focus on CHORD encoding")
  
  return missing_elements, extra_elements


class ChordComparisonFunctions:
  pass


def get_chord_info(element):
  """Get detailed chord information"""
  if is_chord(element):
    return {
      'type': 'chord',
      'pitches': tuple(sorted([p.midi for p in element.pitches])),
      'pitch_names': tuple(sorted([p.name for p in element.pitches])),
      'note_count': len(element.pitches),
      'root': element.root().name if len(element.pitches) > 0 else None,
      'bass': element.bass().name if len(element.pitches) > 0 else None,
      'duration': element.duration.quarterLength,
      'offset': element.offset,
      'is_grace': is_grace_note(element)
    }
  elif hasattr(element, 'pitch'):  # Single note
    return {
      'type': 'note',
      'pitches': (element.pitch.midi,),
      'pitch_names': (element.pitch.name,),
      'note_count': 1,
      'root': element.pitch.name,
      'bass': element.pitch.name,
      'duration': element.duration.quarterLength,
      'offset': element.offset,
      'is_grace': is_grace_note(element)
    }
  else:
    return None


def compare_chord_structures(chord1, chord2):
  """Compare two chord structures and identify differences"""
  info1 = get_chord_info(chord1)
  info2 = get_chord_info(chord2)
  
  if not info1 or not info2:
    return None
  
  differences = []
  
  # Type change (note ↔ chord)
  if info1['type'] != info2['type']:
    differences.append(f"Type change: {info1['type']} → {info2['type']}")
  
  # Note count change
  if info1['note_count'] != info2['note_count']:
    differences.append(f"Note count: {info1['note_count']} → {info2['note_count']}")
  
  # Pitch changes
  pitches1 = set(info1['pitches'])
  pitches2 = set(info2['pitches'])
  
  added_pitches = pitches2 - pitches1
  removed_pitches = pitches1 - pitches2
  
  if added_pitches:
    added_names = [music21.pitch.Pitch(midi=p).name for p in added_pitches]
    differences.append(f"Added pitches: {added_names}")
  
  if removed_pitches:
    removed_names = [music21.pitch.Pitch(midi=p).name for p in removed_pitches]
    differences.append(f"Removed pitches: {removed_names}")
  
  return {
    'identical': len(differences) == 0,
    'differences': differences,
    'info1': info1,
    'info2': info2
  }


def diagnose_chord_differences(file1, file2):
  """Comprehensive chord difference analysis"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== CHORD STRUCTURE ANALYSIS ===")
  
  elements1 = list(score1.flat.notesAndRests)
  elements2 = list(score2.flat.notesAndRests)
  
  # Filter to notes and chords only
  musical_elements1 = [e for e in elements1 if hasattr(e, 'pitch') or is_chord(e)]
  musical_elements2 = [e for e in elements2 if hasattr(e, 'pitch') or is_chord(e)]
  
  if len(musical_elements1) != len(musical_elements2):
    print(f"⚠️  Musical element count mismatch: {len(musical_elements1)} vs {len(musical_elements2)}")
    return
  
  # Count chord vs note types
  chords1 = [e for e in musical_elements1 if is_chord(e)]
  notes1 = [e for e in musical_elements1 if hasattr(e, 'pitch') and not is_chord(e)]
  chords2 = [e for e in musical_elements2 if is_chord(e)]
  notes2 = [e for e in musical_elements2 if hasattr(e, 'pitch') and not is_chord(e)]
  
  print(f"Original: {len(chords1)} chords, {len(notes1)} single notes")
  print(f"Decoded:  {len(chords2)} chords, {len(notes2)} single notes")
  
  chord_differences = []
  type_changes = []
  pitch_changes = []
  
  for i, (e1, e2) in enumerate(zip(musical_elements1, musical_elements2)):
    comparison = compare_chord_structures(e1, e2)
    
    if comparison and not comparison['identical']:
      measure1 = get_measure_number(score1, e1)
      measure2 = get_measure_number(score2, e2)
      
      chord_differences.append({
        'index': i,
        'comparison': comparison,
        'measure1': measure1,
        'measure2': measure2
      })

      # Categorize the type of difference
      if any('Type change' in diff for diff in comparison['differences']):
        type_changes.append(i)
      if any('pitches' in diff for diff in comparison['differences']):
        pitch_changes.append(i)
  
  print(f"\nChord structure differences: {len(chord_differences)}")
  print(f"  Type changes (note ↔ chord): {len(type_changes)}")
  print(f"  Pitch content changes: {len(pitch_changes)}")
  
  # Show detailed examples
  print(f"\n=== DETAILED CHORD DIFFERENCES (first 10) ===")
  for i, diff in enumerate(chord_differences[:10]):
    idx = diff['index']
    comp = diff['comparison']
    info1 = comp['info1']
    info2 = comp['info2']
    
    print(f"\nElement {idx} in Measure {diff['measure1']}:")
    print(f"  Original: {info1['type']} - {info1['pitch_names']} ({info1['note_count']} notes)")
    print(f"  Decoded:  {info2['type']} - {info2['pitch_names']} ({info2['note_count']} notes)")
    print(f"  Changes: {'; '.join(comp['differences'])}")
  
  return chord_differences


def analyze_chord_patterns(file1, file2):
  """Analyze patterns in chord encoding/decoding"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  elements1 = [e for e in score1.flat.notesAndRests if hasattr(e, 'pitch') or is_chord(e)]
  elements2 = [e for e in score2.flat.notesAndRests if hasattr(e, 'pitch') or is_chord(e)]
  
  # Pattern analysis
  note_to_chord = 0  # Single note became chord
  chord_to_note = 0  # Chord became single note
  chord_size_changes = []
  
  for e1, e2 in zip(elements1, elements2):
    info1 = get_chord_info(e1)
    info2 = get_chord_info(e2)
    
    if info1 and info2:
      if info1['type'] == 'note' and info2['type'] == 'chord':
        note_to_chord += 1
      elif info1['type'] == 'chord' and info2['type'] == 'note':
        chord_to_note += 1
      elif info1['type'] == 'chord' and info2['type'] == 'chord':
        if info1['note_count'] != info2['note_count']:
          chord_size_changes.append((info1['note_count'], info2['note_count']))
  
  print("=== CHORD PATTERN ANALYSIS ===")
  print(f"Single notes converted to chords: {note_to_chord}")
  print(f"Chords converted to single notes: {chord_to_note}")
  print(f"Chord size changes: {len(chord_size_changes)}")
  
  if chord_size_changes:
    print("Chord size change patterns:")
    size_change_counts = {}
    for old, new in chord_size_changes:
      change = f"{old}→{new}"
      size_change_counts[change] = size_change_counts.get(change, 0) + 1
    
    for change, count in sorted(size_change_counts.items(), key=lambda x: x[1], reverse=True):
      print(f"  {change} notes: {count} times")



class OffsetComparisonFunctions:
  pass


def compare_offsets(file1, file2, tolerance=0.001):
  """Comprehensive offset/timing comparison"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== OFFSET/TIMING ANALYSIS ===")
  
  elements1 = list(score1.flat.notesAndRests)
  elements2 = list(score2.flat.notesAndRests)
  
  musical_elements1 = [e for e in elements1 if hasattr(e, 'pitch') or is_chord(e)]
  musical_elements2 = [e for e in elements2 if hasattr(e, 'pitch') or is_chord(e)]
  
  if len(musical_elements1) != len(musical_elements2):
    print(f"⚠️  Element count mismatch: {len(musical_elements1)} vs {len(musical_elements2)}")
    return
  
  offset_differences = []
  duration_differences = []
  timing_shifts = []
  
  for i, (e1, e2) in enumerate(zip(musical_elements1, musical_elements2)):
    offset_diff = e2.offset - e1.offset
    duration_diff = e2.duration.quarterLength - e1.duration.quarterLength
    measure_number = get_measure_number(score1, e1)
    
    if abs(offset_diff) > tolerance:
      offset_differences.append({
        'index': i,
        'original_offset': float(e1.offset),
        'decoded_offset': float(e2.offset),
        'difference': float(offset_diff),
        'element_type': 'chord' if is_chord(e1) else 'note',
        'pitch_info': get_chord_info(e1)['pitch_names'] if get_chord_info(e1) else None,
        'measure': measure_number,
      })
      timing_shifts.append(offset_diff)
    
    if abs(duration_diff) > tolerance:
      duration_differences.append({
        'index': i,
        'original_duration': e1.duration.quarterLength,
        'decoded_duration': e2.duration.quarterLength,
        'difference': duration_diff,
        'element_type': 'chord' if is_chord(e1) else 'note',
        'measure': measure_number,
      })
  
  print(f"Offset differences (>{tolerance}): {len(offset_differences)}")
  print(f"Duration differences (>{tolerance}): {len(duration_differences)}")
  
  # Analyze timing shift patterns
  if timing_shifts:
    print(f"\n=== TIMING SHIFT ANALYSIS ===")
    avg_shift = sum(timing_shifts) / len(timing_shifts)
    print(f"Average timing shift: {avg_shift:.6f} quarter notes")
    
    # Check for systematic shift
    if abs(avg_shift) > tolerance:
      if avg_shift > 0:
        print(f"  → Systematic delay: decoded notes are {avg_shift:.6f} quarter notes later")
      else:
        print(f"  → Systematic advance: decoded notes are {abs(avg_shift):.6f} quarter notes earlier")
    
    # Check for consistent shifts
    unique_shifts = list(set(round(shift, 6) for shift in timing_shifts))
    if len(unique_shifts) == 1:
      print(f"  → All shifts are identical: {unique_shifts[0]:.6f}")
    elif len(unique_shifts) <= 3:
      print(f"  → Limited shift values: {unique_shifts}")
    else:
      print(f"  → Variable shifts: {len(unique_shifts)} different values")
  
  # Show detailed examples
  print(f"\n=== DETAILED OFFSET DIFFERENCES (first 10) ===")
  for i, diff in enumerate(offset_differences[:10]):
    idx = diff['index']
    print(f"Element {idx} ({diff['element_type']}) in Measure {diff['measure']}:")
    print(f"  Pitches: {diff['pitch_info']}")
    print(f"  Offset: {diff['original_offset']:.6f} → {diff['decoded_offset']:.6f}")
    print(f"  Difference: {diff['difference']:+.6f} quarter notes")
    
    # Convert to musical terms
    if abs(diff['difference']) >= 1.0:
      beats = abs(diff['difference'])
      print(f"  = {beats:.2f} beats {'later' if diff['difference'] > 0 else 'earlier'}")
    elif abs(diff['difference']) >= 0.5:
      print(f"  = ~half beat {'later' if diff['difference'] > 0 else 'earlier'}")
    elif abs(diff['difference']) >= 0.25:
      print(f"  = ~quarter beat {'later' if diff['difference'] > 0 else 'earlier'}")
  
  print(f"\n=== DETAILED DURATION DIFFERENCES (first 10) ===")
  for i, diff in enumerate(duration_differences[:10]):
    idx = diff['index']
    print(f"Element {idx} ({diff['element_type']}) in Measure {diff['measure']}:")
    print(f"  Duration: {diff['original_duration']:.6f} → {diff['decoded_duration']:.6f}")
    print(f"  Difference: {diff['difference']:+.6f} quarter notes")
  
  return offset_differences, duration_differences


def analyze_rhythmic_patterns(file1, file2):
  """Analyze rhythmic pattern preservation"""
  score1 = music21.converter.parse(file1)
  score2 = music21.converter.parse(file2)
  
  print("=== RHYTHMIC PATTERN ANALYSIS ===")
  
  elements1 = [e for e in score1.flat.notesAndRests if hasattr(e, 'duration')]
  elements2 = [e for e in score2.flat.notesAndRests if hasattr(e, 'duration')]
  
  # Extract rhythm patterns
  durations1 = [e.duration.quarterLength for e in elements1]
  durations2 = [e.duration.quarterLength for e in elements2]
  
  # Find common duration values
  unique_durations1 = set(durations1)
  unique_durations2 = set(durations2)
  
  print(f"Original duration types: {len(unique_durations1)}")
  print(f"Decoded duration types: {len(unique_durations2)}")
  
  # Common duration names
  duration_names = {
    4.0: "whole", 2.0: "half", 1.0: "quarter", 0.5: "eighth", 
    0.25: "sixteenth", 0.125: "thirty-second", 1.5: "dotted half",
    0.75: "dotted quarter", 0.375: "dotted eighth", 3.0: "dotted whole"
  }
  
  print(f"\nOriginal durations:")
  for dur in sorted(unique_durations1):
    count = durations1.count(dur)
    name = duration_names.get(dur, f"{dur} quarters")
    print(f"  {name}: {count} times")
  
  print(f"\nDecoded durations:")
  for dur in sorted(unique_durations2):
    count = durations2.count(dur)
    name = duration_names.get(dur, f"{dur} quarters")
    print(f"  {name}: {count} times")
  
  # Check for duration quantization issues
  lost_durations = unique_durations1 - unique_durations2
  gained_durations = unique_durations2 - unique_durations1
  
  if lost_durations:
    print(f"\nLost duration types:")
    for dur in sorted(lost_durations):
      name = duration_names.get(dur, f"{dur} quarters")
      print(f"  {name}")
  
  if gained_durations:
    print(f"\nGained duration types:")
    for dur in sorted(gained_durations):
      name = duration_names.get(dur, f"{dur} quarters")
      print(f"  {name}")


def comprehensive_timing_analysis(file1, file2, tolerance=0.001):
  """Combined analysis of all timing-related issues"""
  print("=== COMPREHENSIVE TIMING ANALYSIS ===")
  
  # 1. Basic offset comparison
  offset_diffs, duration_diffs = compare_offsets(file1, file2, tolerance=tolerance)
  
  print(f"\n")
  
  # 2. Rhythmic pattern analysis
  analyze_rhythmic_patterns(file1, file2)


